query CartTransformRunInput {
  cart {
    lines {
      id
      quantity
      sellingPlanAllocation { sellingPlan { id } }
      cost {
        amountPerQuantity {
          amount
          currencyCode
        }
      }
      bundleSelection: attribute(key: "_sb") {
        value
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          bundleMemberships: metafield(namespace: "$app", key: "bundle_memberships") { jsonValue }
          product {
            bundleRuntime: metafield(namespace: "$app", key: "bundle_runtime") {
              jsonValue
            }
          }
        }
      }
    }
  }
}
