query CartTransformRunInput {
  presentmentCurrencyRate
  cart {
    lines {
      id
      cost {
        amountPerQuantity {
          currencyCode
        }
      }
      bundleSelection: attribute(key: "_sb") {
        value
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            bundleRuntime: metafield(namespace: "$app", key: "bundle_runtime") {
              jsonValue
            }
          }
        }
      }
    }
  }
}
